name: Build OCJS

on:
  workflow_dispatch:
    inputs:
      buildType:
        type: choice
        description: Type of build
        options:
          - testBindings
          - dryRun
          - release
      multithreaded:
        type: boolean
        description: Include Multi-Threaded build?

jobs:
  build:
    name: Build OpenCascade.js
    runs-on: [self-hosted, full]
    timeout-minutes: 10000
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Generate version number
        id: version
        run: |
          if [ "${{ github.event.inputs.buildType }}" == "release" ]
          then
            export NEW_OPENCASCADEJS_VERSION=$(node -p -e "require('./package.json').version.split('-')[0]")-beta.$(git log --pretty=format:'%h' -n 1)
            echo "::set-output name=version::$NEW_OPENCASCADEJS_VERSION"
            echo "::set-output name=tags::${{ secrets.DOCKER_IMAGE_NAME }}:$NEW_OPENCASCADEJS_VERSION,${{ secrets.DOCKER_IMAGE_NAME }}:latest"
            githubRef=${{ github.ref }}
            githubBranch=$(echo "${githubRef##*/}")
            lowerCaseBranchName=$(echo "$githubBranch" | tr '[:upper:]' '[:lower:]')
            echo $lowerCaseBranchName
            echo "::set-output name=lowerCaseBranchName::$lowerCaseBranchName"
          else
            echo "::set-output name=tags::${{ secrets.DOCKER_IMAGE_NAME }}:latest"
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: NPM install tests
        run: |
          cd test
          npm install
          cd ..

      - name: Build OpenCascade.js Docker Image "testImage" and run binding tests
        timeout-minutes: 10000
        run: |
          docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:latest || true
          docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }} || true
          docker build --target testImage --build-arg threading=single-threaded -t ${{ secrets.DOCKER_IMAGE_NAME }}-test-image --cache-from ${{ secrets.DOCKER_IMAGE_NAME }}:latest --cache-from ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }} .
          cd test
          bindingsTestImage="donalffons/opencascade.js-test-image" npm run test -- ./testBindings.test.ts
          cd ..

      - name: Build OpenCascade.js Docker Image "customBuildImage"
        if: github.event.inputs.buildType != 'testBindings'
        timeout-minutes: 10000
        run: |
          docker build --target customBuildImage --build-arg threading=single-threaded -t ${{ secrets.DOCKER_IMAGE_NAME }} --cache-from ${{ secrets.DOCKER_IMAGE_NAME }}:latest --cache-from ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }} .

      - name: Push to Docker Hub (staging)
        if: github.event.inputs.buildType != 'testBindings'
        run: |
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }} ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }}
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }}

      - name: Build OpenCascade.js Full Module
        if: github.event.inputs.buildType != 'testBindings'
        timeout-minutes: 10000
        run: |
          docker run \
            -v $(pwd):/src \
            -u $(id -u):$(id -g) \
            ${{ secrets.DOCKER_IMAGE_NAME }} \
            /src/builds/opencascade.full.yml
          cp opencascade.full.* dist

      - name: Run all tests
        if: github.event.inputs.buildType != 'testBindings'
        run: |
          cd test
          npm run test

      - name: Build OpenCascade.js Docker Image (Multi-Threaded)
        if: github.event.inputs.buildType != 'testBindings' && github.event.inputs.multithreaded == 'true'
        timeout-minutes: 10000
        run: |
          docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:multi-threaded || true
          docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }}-multi-threaded || true
          docker build --target customBuildImage --build-arg threading=multi-threaded -t ${{ secrets.DOCKER_IMAGE_NAME }}:multi-threaded --cache-from ${{ secrets.DOCKER_IMAGE_NAME }}:multi-threaded --cache-from ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }}-multi-threaded .

      - name: Push to Docker Hub (Staging, Multi-Threaded)
        if: github.event.inputs.buildType != 'testBindings' && github.event.inputs.multithreaded == 'true'
        run: |
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:multi-threaded ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }}-multi-threaded
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:staging-${{ steps.version.outputs.lowerCaseBranchName }}-multi-threaded

      - uses: actions/upload-artifact@v2
        if: github.event.inputs.buildType != 'testBindings'
        with:
          name: dist
          path: ./dist/

      - name: Push to Docker Hub
        if: github.event.inputs.buildType == 'release'
        run: |
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }} ${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.version }}
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.version }}

      - name: Push to Docker Hub (Multi-Threaded)
        if: github.event.inputs.buildType == 'release' && github.event.inputs.multithreaded == 'true'
        run: |
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:multi-threaded
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:multi-threaded ${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.version }}-multi-threaded
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.version }}-multi-threaded

      - name: Git and NPM config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish new beta version to NPM
        if: github.event.inputs.buildType == 'release'
        run: |
          npm version ${{ steps.version.outputs.version }} --force
          npm publish --tag=beta

      - name: Git pull
        run: |
          git pull

      - name: Push Changes to branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
