name: Deploy website to preview channel on PR

'on': pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Add reference docs to website
        run: |
          cd website/src/.vuepress/public
          gsutil cp gs://opencascade-js/reference-docs.zip .
          unzip reference-docs.zip
          rm reference-docs.zip
      - name: build website
        run: |
          cd website
          npm ci
          npm run build
          npm run disallow-search-bots
      - name: Deploy to firebase preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OPENCASCADE_JS }}'
          projectId: opencascade-js
          entryPoint: website
          expires: 30d
