name: General CI/CD Jobs

on:
  push:
    branches:
      - beta

jobs:
  general:
    name: General CI/CD Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: donalffons/opencascade.js
