name: General CI/CD Jobs

on:
  push:
    branches:
      - master

jobs:
  general:
    name: General CI/CD Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_IMAGE_NAME }}
  website:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Add reference docs to website
        run: |
          cd website/static
          gsutil cp gs://opencascade-js/reference-docs.zip .
          unzip reference-docs.zip
          rm reference-docs.zip
      - name: Build website
        run: |
          cd website
          npm ci
          cd ocjs-editor-theme
          npm ci
          cd ..
          npm run build
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OPENCASCADE_JS }}'
          channelId: live
          projectId: opencascade-js
          entryPoint: website
