name: Run Tests

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run tests
        run: |
          cd test
          npm install
          npm install opencascade.js@beta
          npm run test
  