name: Run Tests

on: workflow_dispatch

jobs:
  test:
    name: Run tests
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run tests
        run: |
          cd test
          npm install
          npm install opencascade.js@beta
          npm run test
  