name: Update Reference Docs

on:
  workflow_dispatch:

jobs:
  update:
    name: Update Reference Docs
    runs-on: [self-hosted, referenceDocs]
    timeout-minutes: 10000
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          gcloud components install beta
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Download Latest OpenCascade.js Release
        run: |
          cd dist
          npm view opencascade.js@beta dist.tarball | xargs curl | tar -xz
          cd package
          mv dist/* ../
          cd ..
          rm package -r
          cd ..
      - name: Update Reference Docs
        timeout-minutes: 10000
        run: |
          apt-get update
          apt-get install -y zip
          cd typedoc-reference-docs
          npm ci && npm run build -- --out ./reference-docs
          zip -r reference-docs.zip ./reference-docs
          gsutil cp ./reference-docs.zip gs://opencascade-js/reference-docs.zip
          rm ./reference-docs.zip
